# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My awesome site
email: ka.boyd@ulster.ac.uk
description: "totes amaze"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
tagline: This is the best site I have ever seen
twitter_username: kylbyd
github_username:  kyleboyd


# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
